# This is a basic workflow to help you get started with Actions

name: Build AdguardHome binary for armv7-softfloat

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      GO_VERSION: '1.24.1'
      NODE_VERSION: '18'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      name: checkout repo

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '${{ env.GO_VERSION }}'

    - name: setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${{ env.NODE_VERSION }}'

    - name: Set up QEMU for arm compilation
      uses: docker/setup-qemu-action@v1

    - name: Build binary
      # id is used for passing tags in the following steps
      id: get_latest_tag
      run: |
        git clone https://github.com/AdguardTeam/AdGuardHome.git
        cd AdGuardHome
        latest_tag=$(curl -s https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest | jq -r '.tag_name')
        echo "Latest stable tag: $latest_tag"
        echo "::set-output name=tag::$latest_tag"
        git checkout $latest_tag
        env GOOS='linux' GOARCH='arm' GOARM='7,softfloat' make
        ls -al

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_latest_tag.outputs.tag }}
        body: "AdGuardHome arm 7,softfloat ${{ steps.get_latest_tag.outputs.tag }}"
        files: "./AdGuardHome/AdGuardHome"
